import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavMenu from '@/app/NavMenu';
import AuthProvider from './AuthProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <AuthProvider>
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <NavMenu />
          <main>{children}</main>
        </div>
      </body>
    </html>
    </AuthProvider>
  )
}
